# Site settings
title: technologies2000
email: georgereddykg@gmail.com
description: Technologies2000 is a Quality, IT Services, Cell Phones, and services, Wealth and Health builders, Social
             media, and differect ventures. We haven been serving since 1993 and servied many fortune 500 companies.
baseurl: /technologies2000
url: 
twitter_username: GeorgeReddykg
github_username:  kgreddy

# Build settings
markdown: kramdown
